from pathlib import Path

# Config variables
FILES_FOLDER = Path(__file__).parent / 'files'
EXAMPLES_FOLDER = Path(__file__).parent / 'examples'
OUTPUT_FOLDER = Path(__file__).parent / 'outputs'
VECTOR_DB_FOLDER = Path(__file__).parent / 'vector_db'
EMBEDDING_MODEL = "text-embedding-ada-002"
COLLECTION_NAME = "RO_LORE_COMPEDIUM"
MODEL_NAME = "gpt-5.4-mini"


# Lore related variables
ALIGNMENT_OPTIONS = [
    "Lawful Good",
    "Neutral Good",
    "Chaotic Good",
    "Lawful Neutral",
    "True Neutral",
    "Chaotic Neutral",
    "Lawful Evil",
    "Neutral Evil",
    "Chaotic Evil"
]
CLASSES_OPTIONS = [
"Novice",
"Super Novice",
"Swordsman",
"Mage",
"Archer",
"Merchant",
"Thief",
"Acolyte",
"Knight",
"Wizard",
"Hunter",
"Blacksmith",
"Assassin",
"Priest",
"Crusader",
"Sage",
"Bard",
"Dancer",
"Alchemist",
"Rogue",
"Monk",
"Lord Knight",
"High Wizard",
"Sniper",
"Whitesmith",
"Assassin Cross",
"High Priest",
"Paladin",
"Scholar",
"Minstrel",
"Gypsy",
"Biochemist",
"Stalker",
"Champion",
"Rune Knight",
"Warlock",
"Ranger",
"Mechanic",
"Guillotine Cross",
"Arch Bishop",
"Royal Guard",
"Sorcerer",
"Maestro",
"Wanderer",
"Geneticist",
"Shadow Chaser",
"Sura",
"Taekwon",
"Ninja",
"Gunslinger",
"Taekwon Master",
"Soul Linker",
"Soul Reaper",
"Kagerou",
"Oboro",
"Rebel"
]
GENDER_OPTIONS= ["Female", "Male", "Other"]
LOCATIONS_OPTIONS= [
    "Prontera",
    "Izlude",
    "Geffen",
    "Payon",
    "Morroc",
    "Alberta",
    "Al De Baran",
    "Comodo",
    "Umbala",
    "Juno (Yuno)",
    "Einbroch",
    "Einbech",
    "Lighthalzen",
    "Hugel",
    "Rachel",
    "Veins",
    "Amatsu",
    "Ayothaya",
    "Louyang",
    "Kunlun (Gonryun)",
    "Brasilis",
    "Dewata",
    "Moscovia",
    "Port Malaya",
    "Rock Ridge",
    "Lutie",
    "Niflheim",
    "Jawaii",
    "Malangdo",
    "Lasagna",
    "Midcamp",
    "Splendide",
    "Manuk",
    "El Dicastes",
    "Mora",
    "Eclage",
    "Cor",
    "Glast Heim",
    "St. Capitolina Abbey",
    "Mt. Mjolnir",
    "The Assassin Guild",
    "The Pyramids & The Sphinx",
    "The Sograt Desert",
    "Juperos Ruins",
    "Thanatos Tower",
    "Odin's Temple",
    "Abyss Lake",
    "Byalan Island / Undersea Tunnel",
    "Kiel Hyre's Academy"
]